#!/bin/bash

# Games included:
# Russian Roulette
# Coinflip
# Rock Paper Scissors 

# Game Function Definitions #

# COINFLIP #
function coinflip() {
	RANDINT=$(($RANDOM%2))
	if [[ $RANDINT == 1  ]]; then
		echo "Heads"
	else echo "Tails"
	fi
}
# RUSSIAN ROULETTE #
function russianroulette() {
	RANDINT=$(($RANDOM%6))
	function game() {
		echo "*click*"
		if [[ $RANDINT -ne 0 ]]; then

			echo "You live, do you wish to push your luck?: [Y/n]"
			read luck
			if [[ $luck == y ]] || [[ $luck == Y  ]]; then
				shoot
			elif [[ $luck == n ]] || [[ $luck == N ]]; then
				echo "// Ending game..."
				echo "// You were" $RANDINT "shot(s) away from losing!"
			else
				echo "// Unknown input... assuming no."
				echo "// You were" $RANDINT "shot(s) away from losing!"
			fi
		else
			echo "*BANG!!*"
			echo "// You Died! Ending game..."
		fi
	}
	function shoot() {
		RANDINT=$(($RANDINT - 1))
		game
	}
	game
}

# ROCK PAPER SCISSORS #
function RockPaperScissors(){
	echo "CHOICES: {rock | paper | scissors}"
	read throw
	# Parse User Input to make it lowercase
	if [[ $throw == "ROCK" ]] || [[ $throw == "rock" ]]; then
		throw="rock"
	elif [[ $throw == "PAPER" ]] || [[ $throw == "paper" ]]; then
		throw="paper"
	elif [[ $throw == "SCISSORS" ]] || [[ $throw == "scissors" ]]; then
		throw="scissors"
	else
		echo "unknown input"
	fi

	# AI adversary
	RANDINT=$(($RANDOM%3))
	if [[ $RANDINT == 0 ]]; then
		adv="rock"
	elif [[ $RANDINT == 1  ]]; then
		adv="scissors"
	else
		adv="paper"
	fi
	# Win Conditions
	if [[ $throw == "rock" && $adv == "scissors" ]] || [[ $throw == "paper" && $adv == "rock" ]] || [[ $throw == "scissors" && $adv == "paper" ]]; then
		echo $throw ">" $adv
		echo "You Win!" 
	# Lose conditions
	elif [[ $throw == "scissors" && $adv == "rock" ]] || [[ $throw == "rock" && $adv == "paper" ]] || [[ $throw == "paper" && $adv == "scissors" ]]; then
		echo $throw "<" $adv
		echo "You Lose..."
	elif [[ $throw == $adv ]]; then
		echo $throw "=" $adv
		echo "It's a Tie!"
	fi
	}
# choosing a game # 

function mainmenu() {
	echo -e "// What game would you like to play? \n ENTER CHOICE NUMBER: "
	echo "// 1.) Russian Roulette"
	echo "// 2.) Coinflip"
	echo "// 3.) Rock Paper Scissors"
	read choice
	if [[ $choice == 1  ]]; then
		russianroulette
	elif [[ $choice == 2 ]]; then 
		coinflip
	elif [[ $choice == 3 ]]; then
		RockPaperScissors
	else
		echo "// Unknown choice, please enter a valid choice"
		mainmenu
	fi
	echo "// ending script"
}
echo "// Main Menu"
mainmenu
